---

- hosts: all
  become: true
  tasks:

  - name: install qemu-guest-agent apache and php
    package:
      name:
        - "{{ qemu_agent }}"
        - "{{ apache_package }}"
        - "{{ php }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: yes


