---

- hosts: all
  become: true
  tasks:
    
  - name: remove libapache-mod2-php php apache2 package2 and mariadb-server packages
    package:
      name: 
        - apache2
        - php
        - libapache2-mod-php
        - mariadb-server
        - samba
      state: absent


