---

- hosts: all
  become: true
  tasks:

  - name: remove libapache-mod2-php php apache2 package2 mariadb-server samba and cockpit packages
    package:
      name:
        - apache2
        - php
        - libapache2-mod-php
        - mariadb-server
        - samba
        - nfs-common
        - cockpit
      state: absent

  - name: remove user sushi
    ansible.builtin.user:
      name: sushi
      state: "absent"
      remove: true

  - name: Clean unwanted olderstuff
    apt:
     autoremove: yes
     purge: yes
