---

- hosts: all
  become: true
  tasks:
    
  - name: remove libapache-mod2-php php and apache2 package2
    apt:
      name: 
        - libapache-mod2-php
        - php
        - apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

