---

- hosts: all
  become: true
  tasks:
    
  - name: remove libapache-mod2-php php and apache2 package2
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php }}"
        - "{{ php_package }}"
      state: absent


