---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install qemu-guest-agent and cockpit
    package:
      name: 
         - qemu-guest-agent
         - cockpit
      state: latest
      update_cache: yes 
    when: ansible_distribution == "Ubuntu" 

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache and php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    apt: 
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" 

- hosts: file_servers
  become: true
  tasks:

  - name: install samba and packages
    apt:
      name:  
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"
