---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install cockpit and nfs-common
    tags: always
    package:
      name:
         - cockpit
         - nfs-common
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: terraform_servers
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: qemu_virtual_machines
  become: true
  tasks:

  - name: install qemu-guest-agent
    tags: qemu-guest
    package:
      name: qemu-guest-agent
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: apache, ubuntu, web_servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: web_servers
    copy:
      src: files/
      dest: /var/www/html/
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db, mariadb, ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba and packages
    tags: file_servers, samba
    apt:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: laptops
  tags: laptops, wireguard
  become: true
  tasks:

  - name: install wireguard client
    apt:
      name:
        - wireguard
      state: latest
    when: ansible_distribution == "Ubuntu"
